### ISSUE TITLE
Desafios Full Stack - Java: Cofres Seguros

### ISSUE THREAD

**Issue by laineanalistasistemas** [CarlosEduardoLemos/Desafios-Bootcamp2023#1]
Uma ajudinha nesse desafio, pois esta meio dificil de achar o erro..

**Comment by danielreis07** [comment]
import java.text.DecimalFormat;
import java.util.Scanner;

class ContaBancaria {
    private int numeroConta;
    private String titular;
    private double saldo;

    public ContaBancaria(int numeroConta, String titular, double saldo) {
        this.numeroConta = numeroConta;
        this.titular = titular;
        this.saldo = saldo;
    }

    public int getNumeroConta() {
        return numeroConta;
    }

    public String getTitular() {
        return titular;
    }

    public double getSaldo() {
        return saldo;
    }
}

class ContaPoupanca extends ContaBancaria {
    private double taxaJuros;

    public ContaPoupanca(int numeroConta, String titular, double saldo, double taxaJuros) {
        super(numeroConta, titular, saldo);
        this.taxaJuros = taxaJuros;
    }

    public double getTaxaJuros() {
        return taxaJuros;
    }

    public void exibirInformacoes() {
        DecimalFormat df = new DecimalFormat("0.0");
        System.out.println("Conta Poupanca:");
        System.out.println(getTitular());
        System.out.println(getNumeroConta());
        System.out.println("Saldo: R$ " + df.format(getSaldo()));
        System.out.println("Taxa de juros: " + df.format(getTaxaJuros()) + "%");
    }
}

public class Main {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        while (scanner.hasNext()) {
            String titular = scanner.nextLine();
            int numeroConta = Integer.parseInt(scanner.nextLine());
            double saldo = Double.parseDouble(scanner.nextLine());
            double taxaJuros = Double.parseDouble(scanner.nextLine());

            ContaPoupanca contaPoupanca = new ContaPoupanca(numeroConta, titular, saldo, taxaJuros);
            contaPoupanca.exibirInformacoes();
        }

        scanner.close();
    }
}

**Comment by CarlosEduardoLemos** [comment]
Foi adicionado os 5 desafios de java dos desafios bancários.

**Comment by CarlosEduardoLemos** [comment]
> Uma ajudinha nesse desafio, pois esta meio dificil de achar o erro..

Adicionei os 5 desafios. O código para esse desafio está em [Desafio03.java](https://github.com/CarlosEduardoLemos/Desafios-Bootcamp2023/blob/main/Java/Desafio03.java)
